In [2]:
import pandas as pd

df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
})

df2 = pd.DataFrame({
    "ID": [4, 5, 6],
    "Name": ["David", "Eve", "Frank"],
    "Age": [40, 50, 60]
})

print(df1)
print()
print(df2)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

   ID   Name  Age
0   4  David   40
1   5    Eve   50
2   6  Frank   60

In [3]:
# Concatenatin verically (default axis=0)
result = pd.concat([df1, df2])
result

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
0   4    David   40
1   5      Eve   50
2   6    Frank   60

In [4]:
result.reset_index(drop=True)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eve   50
5   6    Frank   60

In [5]:
df3 = pd.DataFrame({
    "Salary": [50000, 60000, 70000]
})
print(df3)

   Salary
0   50000
1   60000
2   70000

In [6]:
# Concatenating horizontally
result = pd.concat([df1, df3], axis=1)
result

   ID     Name  Age  Salary
0   1    Alice   25   50000
1   2      Bob   30   60000
2   3  Charlie   35   70000

In [7]:
df4 = pd.DataFrame({
    "ID": [7, 8],
    "Salary": [55000, 75000]
})

# Concatenating with missing columns
print(df1)
print(df4)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
   ID  Salary
0   7   55000
1   8   75000

In [8]:
result = pd.concat([df1, df4], axis=0)
print(result)

   ID     Name   Age   Salary
0   1    Alice  25.0      NaN
1   2      Bob  30.0      NaN
2   3  Charlie  35.0      NaN
0   7      NaN   NaN  55000.0
1   8      NaN   NaN  75000.0

In [9]:
import numpy as np

In [10]:
result.isna()

      ID   Name    Age  Salary
0  False  False  False    True
1  False  False  False    True
2  False  False  False    True
0  False   True   True   False
1  False   True   True   False

In [11]:
assert np.all(result.isna()), "0 voch"

AssertionError: 0 voch

Concatenatin with keys (multi-index)

In [12]:
print(df1)
print()
print(df2)

result = pd.concat([df1, df2], keys=["Group 1", "Group 2"], axis=0)
print(result)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

   ID   Name  Age
0   4  David   40
1   5    Eve   50
2   6  Frank   60
           ID     Name  Age
Group 1 0   1    Alice   25
        1   2      Bob   30
        2   3  Charlie   35
Group 2 0   4    David   40
        1   5      Eve   50
        2   6    Frank   60

Merge

In [13]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "bob", "Charlie"],
    "Age": [25, 30, 35] 
})

df5 = pd.DataFrame({
    "ID": [1, 2],
    "Department": ["HR", "IT"]
})

print(df1)
print(df5)

#Merging DataFrames on "ID" column
result = pd.merge(df1, df5, on="ID")
result

   ID     Name  Age
0   1    Alice   25
1   2      bob   30
2   3  Charlie   35
   ID Department
0   1         HR
1   2         IT

   ID   Name  Age Department
0   1  Alice   25         HR
1   2    bob   30         IT

In [14]:
# DataFrame 1
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40]
})

# DataFrame 2
df2 = pd.DataFrame({
    "ID": [3, 4, 5, 6],
    "Department": ["HR", "Finance", "IT", "Marketing"],
    "Salary": [50000, 60000, 70000, 80000]
})

print("DataFrame 1: \n", df1)
print("DataFrame 2: \n", df2)

DataFrame 1:
    ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
DataFrame 2:
    ID Department  Salary
0   3         HR   50000
1   4    Finance   60000
2   5         IT   70000
3   6  Marketing   80000

In [22]:
result_inner = pd.merge(df1, df2, on="ID", how="inner")
print("Inner Join Result: \n", result_inner)

Inner Join Result:
    ID     Name  Age Department  Salary
0   3  Charlie   35         HR   50000
1   4    David   40    Finance   60000

In [ ]:
result_outer = pd.merge(df1, df2, on="ID", how="outer")
print("Outer Join Result: \n", result_outer)

Inner Join Result:
    ID     Name   Age Department   Salary
0   1    Alice  25.0        NaN      NaN
1   2      Bob  30.0        NaN      NaN
2   3  Charlie  35.0         HR  50000.0
3   4    David  40.0    Finance  60000.0
4   5      NaN   NaN         IT  70000.0
5   6      NaN   NaN  Marketing  80000.0

In [ ]:
result_left = pd.merge(df1, df2, on="ID", how="left")
print("Left Join Result: \n", result_left)

Inner Join Result:
    ID     Name  Age Department   Salary
0   1    Alice   25        NaN      NaN
1   2      Bob   30        NaN      NaN
2   3  Charlie   35         HR  50000.0
3   4    David   40    Finance  60000.0

In [ ]:
result_right = pd.merge(df1, df2, on="ID", how="right")
print("Right Join Result: \n", result_right)

Inner Join Result:
    ID     Name   Age Department  Salary
0   3  Charlie  35.0         HR   50000
1   4    David  40.0    Finance   60000
2   5      NaN   NaN         IT   70000
3   6      NaN   NaN  Marketing   80000

Suffixes

In [29]:
df7 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [28, 35, 38]
})

print(df1)
print(df7)
# Merging with suffixe for overlapping columns
result = pd.merge(df1, df7, on="ID", suffixes=("_left", "_right"))
result

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
   ID     Name  Age
0   1    Alice   28
1   2      Bob   35
2   3  Charlie   38

   ID Name_left  Age_left Name_right  Age_right
0   1     Alice        25      Alice         28
1   2       Bob        30        Bob         35
2   3   Charlie        35    Charlie         38

Join

In [34]:
df8 = pd.DataFrame({
    "Salary": [50000, 60000, 70000]
}, index=[1, 2, 3])

# Joining DataFrames on index

print(df1)
print(df8)

result = df1.join(df8)
print(result)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
   Salary
1   50000
2   60000
3   70000
   ID     Name  Age   Salary
0   1    Alice   25      NaN
1   2      Bob   30  50000.0
2   3  Charlie   35  60000.0
3   4    David   40  70000.0

In [36]:
# Inner join (only matching indices)
result = df1.join(df8, how="inner")
print(result)

# Outer join (all rows, NaNs for non-mathces)
result = df1.join(df8, how="outer")
print(result)

   ID     Name  Age  Salary
1   2      Bob   30   50000
2   3  Charlie   35   60000
3   4    David   40   70000
   ID     Name  Age   Salary
0   1    Alice   25      NaN
1   2      Bob   30  50000.0
2   3  Charlie   35  60000.0
3   4    David   40  70000.0

Excel

In [40]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# create a date range for one year of trading data (252 days)
date_range = pd.date_range(end=datetime.today(), periods=252, freq="B")

# Generate synthetic stock data for two different stocks
stock1 = pd.DataFrame({
    "date": date_range,
    "price": (np.random.rand(252) + 0.5).cumprod() * 100,
    "volume": np.random.randint(1000, 10000, 252)
}).set_index("date")

stock2 = pd.DataFrame({
    "date": date_range,
    "price": (np.random.rand(252) + 0.5).cumprod() * 200,
    "volume": np.random.randint(1000, 10000, 252)
}).set_index("date")

# Create a Pandas Excel writer using XlsWriter as the engine
with pd.ExcelWriter("financial_data.xlsx", engine="openpyxl") as writer:
    # Write each DataFrame to a different worksheet
    stock1.to_excel(writer, sheet_name="Stock1")
    stock2.to_excel(writer, sheet_name="Stock2")

Reading Excel files

In [41]:
df = pd.read_excel("financial_data.xlsx")
df

                       date       price  volume
0   2025-05-29 11:38:45.016  148.519798    4244
1   2025-05-30 11:38:45.016  173.555969    7779
2   2025-06-02 11:38:45.016  134.199203    7619
3   2025-06-03 11:38:45.016   82.249128    1139
4   2025-06-04 11:38:45.016   58.087180    5304
..                      ...         ...     ...
247 2026-05-11 11:38:45.016    0.451902    7200
248 2026-05-12 11:38:45.016    0.490067    8591
249 2026-05-13 11:38:45.016    0.446382    7885
250 2026-05-14 11:38:45.016    0.566772    1154
251 2026-05-15 11:38:45.016    0.540573    9618

[252 rows x 3 columns]

In [45]:
# Reading a specific sheet by its name
df = pd.read_excel("financial_data.xlsx", sheet_name="Stock2")
print(df.head)
# Reading a specific sheet by its index
df = pd.read_excel("financial_data.xlsx", sheet_name=1)
print(df.head)

<bound method NDFrame.head of                        date       price  volume
0   2025-05-29 11:38:45.016  295.716979    3402
1   2025-05-30 11:38:45.016  300.441087    3884
2   2025-06-02 11:38:45.016  437.998977    3451
3   2025-06-03 11:38:45.016  508.341699    6703
4   2025-06-04 11:38:45.016  345.116388    9813
..                      ...         ...     ...
247 2026-05-11 11:38:45.016    0.002562    5699
248 2026-05-12 11:38:45.016    0.003517    9160
249 2026-05-13 11:38:45.016    0.004804    8488
250 2026-05-14 11:38:45.016    0.005611    1273
251 2026-05-15 11:38:45.016    0.006805    1769

[252 rows x 3 columns]>
<bound method NDFrame.head of                        date       price  volume
0   2025-05-29 11:38:45.016  295.716979    3402
1   2025-05-30 11:38:45.016  300.441087    3884
2   2025-06-02 11:38:45.016  437.998977    3451
3   2025-06-03 11:38:45.016  508.341699    6703
4   2025-06-04 11:38:45.016  345.116388    9813
..                      ...         ...     ...
247 2026-05-11 11:38:45.016    0.002562    5699
248 2026-05-12 11:38:45.016    0.003517    9160
249 2026-05-13 11:38:45.016    0.004804    8488
250 2026-05-14 11:38:45.016    0.005611    1273
251 2026-05-15 11:38:45.016    0.006805    1769

[252 rows x 3 columns]>

In [49]:
# Reading a subset of columns by their names
df = pd.read_excel("financial_data.xlsx", usecols=["price", "volume"])

print(df.head(1))

# Reading a subset of columns by Excel column letters
df = pd.read_excel("financial_data.xlsx", usecols="B, C")
print(df.head(2))

        price  volume
0  148.519798    4244
        price  volume
0  148.519798    4244
1  173.555969    7779

In [53]:
df = pd.read_excel("financial_data.xlsx", nrows=10, skiprows=[1, 3, 4])
df

                     date       price  volume
0 2025-05-30 11:38:45.016  173.555969    7779
1 2025-06-04 11:38:45.016   58.087180    5304
2 2025-06-05 11:38:45.016   68.766666    2250
3 2025-06-06 11:38:45.016  101.666216    4795
4 2025-06-09 11:38:45.016  150.558227    6716
5 2025-06-10 11:38:45.016  217.439478    4469
6 2025-06-11 11:38:45.016  254.791802    6973
7 2025-06-12 11:38:45.016  321.480068    2726
8 2025-06-13 11:38:45.016  207.414498    9068
9 2025-06-16 11:38:45.016  258.832704    1178

Writing to Excel

In [54]:
df["price_in_AMD"] = df["price"] / 383
df

                     date       price  volume  price_in_AMD
0 2025-05-30 11:38:45.016  173.555969    7779      0.453149
1 2025-06-04 11:38:45.016   58.087180    5304      0.151664
2 2025-06-05 11:38:45.016   68.766666    2250      0.179547
3 2025-06-06 11:38:45.016  101.666216    4795      0.265447
4 2025-06-09 11:38:45.016  150.558227    6716      0.393102
5 2025-06-10 11:38:45.016  217.439478    4469      0.567727
6 2025-06-11 11:38:45.016  254.791802    6973      0.665253
7 2025-06-12 11:38:45.016  321.480068    2726      0.839374
8 2025-06-13 11:38:45.016  207.414498    9068      0.541552
9 2025-06-16 11:38:45.016  258.832704    1178      0.675803

In [55]:
df.to_excel("file.xlsx", sheet_name="Bajnetoms 1")
df.to_excel("file_no_index.xlsx", sheet_name="Bajnetoms 1", index=False)

Multiple sheets

In [56]:
with pd.ExcelWriter("two_sheets.xlsx") as writer:
    df.to_excel(writer, sheet_name="Bajnetomser")
    df.sample(10).to_excel(writer, sheet_name="Patahakan 10 tox")

html

In [60]:
url_women = "https://armstat.am/am/?nid=12&id=19044&submit=%D5%93%D5%B6%D5%BF%D6%80%D5%A5%D5%AC"
url_men = "https://armstat.am/am/?nid=12&id=19045&submit=%D5%93%D5%B6%D5%BF%D6%80%D5%A5%D5%AC"

df_women = pd.read_html(url_women)
df_men =pd.read_html(url_men)

In [61]:
df_women[1]

,թվական,բացարձակ արժեք,նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)
0,2025,-,-
1,2024,49206.0,105.3
2,2023,46728.0,103
3,2022,45373.0,145.6
4,2021,31171.0,70.5
5,2020,44187.0,106.5
6,2019,41486.0,95.6
7,2018,43390.0,88
8,2017,49327.0,97.7
9,2016,50463.0,94.1
10,2015,53601.0,104.9
11,2014,41579.0,92.8
12,2013,55044.0,99.6
13,2012,55246.0,94.1
14,2011,58679.0,89.3
15,2010,65678.0,97.8
16,2009,67177.0,102.4
17,2008,65618.0,102.4
18,2007,64099.0,105.9
19,2006,60549.0,108.8
20,2005,55640.0,113.1
21,2004,49178.0,109.8
22,2003,44780.0,111.8
23,2002,40067.0,108.2
24,2001,37026.0,111.1
25,2000,33325.0,99.8

In [64]:
df_men

,թվական,բացարձակ արժեք,նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)
0,2025,-,-
1,2024,36107.0,108.2
2,2023,33367.0,97.7
3,2022,34140.0,72
4,2021,47432.0,134
5,2020,35403.0,105.8
6,2019,33456.0,90.2
7,2018,37087.0,90
8,2017,41213.0,97.9
9,2016,42095.0,98.1
10,2015,42901.0,99.8
11,2014,38044.0,93.9
12,2013,45810.0,97.5
13,2012,47004.0,97.6
14,2011,48176.0,86.5
15,2010,55669.0,98.5
16,2009,56533.0,101.3
17,2008,55826.0,106.4
18,2007,52489.0,106.2
19,2006,49427.0,108.2
20,2005,45661.0,117.2
21,2004,38961.0,109.2
22,2003,35694.0,104.7
23,2002,34087.0,112.4
24,2001,30320.0,110.7
25,2000,27401.0,96.6

In [62]:
df_men = df_men[1]
df_women = df_women[1]

melt

In [65]:
pd.merge(df_men, df_women, on="թվական", how="outer")

,թվական,բացարձակ արժեք_x,նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_x,բացարձակ արժեք_y,նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_y
0,2000,27401.0,96.6,33325.0,99.8
1,2001,30320.0,110.7,37026.0,111.1
2,2002,34087.0,112.4,40067.0,108.2
3,2003,35694.0,104.7,44780.0,111.8
4,2004,38961.0,109.2,49178.0,109.8
5,2005,45661.0,117.2,55640.0,113.1
6,2006,49427.0,108.2,60549.0,108.8
7,2007,52489.0,106.2,64099.0,105.9
8,2008,55826.0,106.4,65618.0,102.4
9,2009,56533.0,101.3,67177.0,102.4
10,2010,55669.0,98.5,65678.0,97.8
11,2011,48176.0,86.5,58679.0,89.3
12,2012,47004.0,97.6,55246.0,94.1
13,2013,45810.0,97.5,55044.0,99.6
14,2014,38044.0,93.9,41579.0,92.8
15,2015,42901.0,99.8,53601.0,104.9
16,2016,42095.0,98.1,50463.0,94.1
17,2017,41213.0,97.9,49327.0,97.7
18,2018,37087.0,90,43390.0,88
19,2019,33456.0,90.2,41486.0,95.6
20,2020,35403.0,105.8,44187.0,106.5
21,2021,47432.0,134,31171.0,70.5
22,2022,34140.0,72,45373.0,145.6
23,2023,33367.0,97.7,46728.0,103
24,2024,36107.0,108.2,49206.0,105.3
25,2025,-,-,-,-

In [66]:
df = pd.merge(df_men, df_women, on="թվական", how="outer", suffixes=("_men", "_women"))
df

,թվական,բացարձակ արժեք_men,նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_men,բացարձակ արժեք_women,նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_women
0,2000,27401.0,96.6,33325.0,99.8
1,2001,30320.0,110.7,37026.0,111.1
2,2002,34087.0,112.4,40067.0,108.2
3,2003,35694.0,104.7,44780.0,111.8
4,2004,38961.0,109.2,49178.0,109.8
5,2005,45661.0,117.2,55640.0,113.1
6,2006,49427.0,108.2,60549.0,108.8
7,2007,52489.0,106.2,64099.0,105.9
8,2008,55826.0,106.4,65618.0,102.4
9,2009,56533.0,101.3,67177.0,102.4
10,2010,55669.0,98.5,65678.0,97.8
11,2011,48176.0,86.5,58679.0,89.3
12,2012,47004.0,97.6,55246.0,94.1
13,2013,45810.0,97.5,55044.0,99.6
14,2014,38044.0,93.9,41579.0,92.8
15,2015,42901.0,99.8,53601.0,104.9
16,2016,42095.0,98.1,50463.0,94.1
17,2017,41213.0,97.9,49327.0,97.7
18,2018,37087.0,90,43390.0,88
19,2019,33456.0,90.2,41486.0,95.6
20,2020,35403.0,105.8,44187.0,106.5
21,2021,47432.0,134,31171.0,70.5
22,2022,34140.0,72,45373.0,145.6
23,2023,33367.0,97.7,46728.0,103
24,2024,36107.0,108.2,49206.0,105.3
25,2025,-,-,-,-

In [67]:
df.columns

Index(['թվական', 'բացարձակ արժեք_men',
       'նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_men',
       'բացարձակ արժեք_women',
       'նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_women'],
      dtype='object')

In [69]:
df.drop(columns=["նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_men",
                 "նախորդ տարվա համապատասխան ժամանակաշրջանի նկատմամբ (%)_women"],
                 inplace=True)

In [72]:
df.columns

Index(['թվական', 'բացարձակ արժեք_men', 'բացարձակ արժեք_women'], dtype='object')

In [77]:
df.rename(columns={"թվական": "year",
                   "բացարձակ արժեք_men": "men",
                   "բացարձակ արժեք_women": "women"}, inplace=True)

In [78]:
df

    year      men    women
0   2000  27401.0  33325.0
1   2001  30320.0  37026.0
2   2002  34087.0  40067.0
3   2003  35694.0  44780.0
4   2004  38961.0  49178.0
5   2005  45661.0  55640.0
6   2006  49427.0  60549.0
7   2007  52489.0  64099.0
8   2008  55826.0  65618.0
9   2009  56533.0  67177.0
10  2010  55669.0  65678.0
11  2011  48176.0  58679.0
12  2012  47004.0  55246.0
13  2013  45810.0  55044.0
14  2014  38044.0  41579.0
15  2015  42901.0  53601.0
16  2016  42095.0  50463.0
17  2017  41213.0  49327.0
18  2018  37087.0  43390.0
19  2019  33456.0  41486.0
20  2020  35403.0  44187.0
21  2021  47432.0  31171.0
22  2022  34140.0  45373.0
23  2023  33367.0  46728.0
24  2024  36107.0  49206.0
25  2025        -        -

In [79]:
long = pd.melt(df, id_vars=["year"], value_vars=["men", "women"])

In [80]:
long

    year variable    value
0   2000      men  27401.0
1   2001      men  30320.0
2   2002      men  34087.0
3   2003      men  35694.0
4   2004      men  38961.0
5   2005      men  45661.0
6   2006      men  49427.0
7   2007      men  52489.0
8   2008      men  55826.0
9   2009      men  56533.0
10  2010      men  55669.0
11  2011      men  48176.0
12  2012      men  47004.0
13  2013      men  45810.0
14  2014      men  38044.0
15  2015      men  42901.0
16  2016      men  42095.0
17  2017      men  41213.0
18  2018      men  37087.0
19  2019      men  33456.0
20  2020      men  35403.0
21  2021      men  47432.0
22  2022      men  34140.0
23  2023      men  33367.0
24  2024      men  36107.0
25  2025      men        -
26  2000    women  33325.0
27  2001    women  37026.0
28  2002    women  40067.0
29  2003    women  44780.0
30  2004    women  49178.0
31  2005    women  55640.0
32  2006    women  60549.0
33  2007    women  64099.0
34  2008    women  65618.0
35  2009    women  67177.0
36  2010    women  65678.0
37  2011    women  58679.0
38  2012    women  55246.0
39  2013    women  55044.0
40  2014    women  41579.0
41  2015    women  53601.0
42  2016    women  50463.0
43  2017    women  49327.0
44  2018    women  43390.0
45  2019    women  41486.0
46  2020    women  44187.0
47  2021    women  31171.0
48  2022    women  45373.0
49  2023    women  46728.0
50  2024    women  49206.0
51  2025    women        -

In [81]:
long = pd.melt(df, id_vars=["year"], value_vars=["men", "women"],
               var_name="gender", value_name="students")

In [82]:
long

    year gender students
0   2000    men  27401.0
1   2001    men  30320.0
2   2002    men  34087.0
3   2003    men  35694.0
4   2004    men  38961.0
5   2005    men  45661.0
6   2006    men  49427.0
7   2007    men  52489.0
8   2008    men  55826.0
9   2009    men  56533.0
10  2010    men  55669.0
11  2011    men  48176.0
12  2012    men  47004.0
13  2013    men  45810.0
14  2014    men  38044.0
15  2015    men  42901.0
16  2016    men  42095.0
17  2017    men  41213.0
18  2018    men  37087.0
19  2019    men  33456.0
20  2020    men  35403.0
21  2021    men  47432.0
22  2022    men  34140.0
23  2023    men  33367.0
24  2024    men  36107.0
25  2025    men        -
26  2000  women  33325.0
27  2001  women  37026.0
28  2002  women  40067.0
29  2003  women  44780.0
30  2004  women  49178.0
31  2005  women  55640.0
32  2006  women  60549.0
33  2007  women  64099.0
34  2008  women  65618.0
35  2009  women  67177.0
36  2010  women  65678.0
37  2011  women  58679.0
38  2012  women  55246.0
39  2013  women  55044.0
40  2014  women  41579.0
41  2015  women  53601.0
42  2016  women  50463.0
43  2017  women  49327.0
44  2018  women  43390.0
45  2019  women  41486.0
46  2020  women  44187.0
47  2021  women  31171.0
48  2022  women  45373.0
49  2023  women  46728.0
50  2024  women  49206.0
51  2025  women        -

In [83]:
print(long.sort_values("year").set_index(["year", "gender"]))

            students
year gender
2000 men     27401.0
     women   33325.0
2001 women   37026.0
     men     30320.0
2002 men     34087.0
     women   40067.0
2003 women   44780.0
     men     35694.0
2004 men     38961.0
     women   49178.0
2005 women   55640.0
     men     45661.0
2006 men     49427.0
     women   60549.0
2007 women   64099.0
     men     52489.0
2008 men     55826.0
     women   65618.0
2009 women   67177.0
     men     56533.0
2010 men     55669.0
     women   65678.0
2011 women   58679.0
     men     48176.0
2012 men     47004.0
     women   55246.0
2013 women   55044.0
     men     45810.0
2014 men     38044.0
     women   41579.0
2015 women   53601.0
     men     42901.0
2016 women   50463.0
     men     42095.0
2017 men     41213.0
     women   49327.0
2018 women   43390.0
     men     37087.0
2019 men     33456.0
     women   41486.0
2020 women   44187.0
     men     35403.0
2021 men     47432.0
     women   31171.0
2022 women   45373.0
     men     34140.0
2023 men     33367.0
     women   46728.0
2024 women   49206.0
     men     36107.0
2025 men           -
     women         -

Datetime

In [101]:
import matplotlib.cbook as cbook

with cbook.get_sample_data("msft.csv") as fp:
    msft = pd.read_csv(fp)

In [102]:
msft

         Date   Open   High    Low  Close    Volume  Adj. Close*
0   19-Sep-03  29.76  29.97  29.52  29.96  92433800        29.79
1   18-Sep-03  28.49  29.51  28.42  29.50  67268096        29.34
2   17-Sep-03  28.76  28.95  28.47  28.50  47221600        28.34
3   16-Sep-03  28.41  28.95  28.32  28.90  52060600        28.74
4   15-Sep-03  28.37  28.61  28.33  28.36  41432300        28.20
..        ...    ...    ...    ...    ...       ...          ...
60  25-Jun-03  25.64  25.99  25.14  25.26  60483500        25.12
61  24-Jun-03  25.65  26.04  25.52  25.70  51820300        25.56
62  23-Jun-03  26.14  26.24  25.49  25.78  52584500        25.64
63  20-Jun-03  26.34  26.38  26.01  26.33  86048896        26.18
64  19-Jun-03  26.09  26.39  26.01  26.07  63626900        25.92

[65 rows x 7 columns]

In [103]:
msft["Date"] = pd.to_datetime(msft["Date"])
msft

C:\Users\SamBa\AppData\Local\Temp\ipykernel_33672\1471018072.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  msft["Date"] = pd.to_datetime(msft["Date"])

         Date   Open   High    Low  Close    Volume  Adj. Close*
0  2003-09-19  29.76  29.97  29.52  29.96  92433800        29.79
1  2003-09-18  28.49  29.51  28.42  29.50  67268096        29.34
2  2003-09-17  28.76  28.95  28.47  28.50  47221600        28.34
3  2003-09-16  28.41  28.95  28.32  28.90  52060600        28.74
4  2003-09-15  28.37  28.61  28.33  28.36  41432300        28.20
..        ...    ...    ...    ...    ...       ...          ...
60 2003-06-25  25.64  25.99  25.14  25.26  60483500        25.12
61 2003-06-24  25.65  26.04  25.52  25.70  51820300        25.56
62 2003-06-23  26.14  26.24  25.49  25.78  52584500        25.64
63 2003-06-20  26.34  26.38  26.01  26.33  86048896        26.18
64 2003-06-19  26.09  26.39  26.01  26.07  63626900        25.92

[65 rows x 7 columns]

In [104]:
msft.set_index("Date", inplace=True)
msft

             Open   High    Low  Close    Volume  Adj. Close*
Date
2003-09-19  29.76  29.97  29.52  29.96  92433800        29.79
2003-09-18  28.49  29.51  28.42  29.50  67268096        29.34
2003-09-17  28.76  28.95  28.47  28.50  47221600        28.34
2003-09-16  28.41  28.95  28.32  28.90  52060600        28.74
2003-09-15  28.37  28.61  28.33  28.36  41432300        28.20
...           ...    ...    ...    ...       ...          ...
2003-06-25  25.64  25.99  25.14  25.26  60483500        25.12
2003-06-24  25.65  26.04  25.52  25.70  51820300        25.56
2003-06-23  26.14  26.24  25.49  25.78  52584500        25.64
2003-06-20  26.34  26.38  26.01  26.33  86048896        26.18
2003-06-19  26.09  26.39  26.01  26.07  63626900        25.92

[65 rows x 6 columns]

In [105]:
msft.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Adj. Close*'], dtype='object')

In [106]:
msft.drop(columns=["High", "Low", "Open", "Volume", "Adj. Close*"], inplace=True)

In [99]:
msft["Year"] = msft.index.year # 2003
msft["Weekday"] = msft.index.day_name() # "Monday"
msft

             Open  Year    Weekday
Date
2003-09-19  29.76  2003     Friday
2003-09-18  28.49  2003   Thursday
2003-09-17  28.76  2003  Wednesday
2003-09-16  28.41  2003    Tuesday
2003-09-15  28.37  2003     Monday
...           ...   ...        ...
2003-06-25  25.64  2003  Wednesday
2003-06-24  25.65  2003    Tuesday
2003-06-23  26.14  2003     Monday
2003-06-20  26.34  2003     Friday
2003-06-19  26.09  2003   Thursday

[65 rows x 3 columns]

In [107]:
monthly = msft["Close"].resample("M").mean()
monthly

C:\Users\SamBa\AppData\Local\Temp\ipykernel_33672\2846096206.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = msft["Close"].resample("M").mean()

Date
2003-06-30    25.770000
2003-07-31    26.799545
2003-08-31    26.038571
2003-09-30    28.466429
Freq: ME, Name: Close, dtype: float64

Profiling

In [109]:
!pip install sweetviz
!pip install -U ydata-profiling

Collecting sweetviz
  Downloading sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\samba\miniconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\samba\miniconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\samba\miniconda3\lib\site-packages (from sweetviz) (3.10.7)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\samba\miniconda3\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\samba\miniconda3\lib\site-packages (from sweetviz) (1.16.2)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\samba\miniconda3\lib\site-packages (from sweetviz) (3.1.6)
Collecting importlib_resources>=1.2.0 (from sweetviz)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\samba\miniconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\samba\appdata\roaming\python\python313\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\samba\appdata\roaming\python\python313\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\samba\miniconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\samba\miniconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\samba\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\users\samba\appdata\roaming\python\python313\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Downloading sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
   -- ------------------------------------- 1.0/15.1 MB 3.7 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/15.1 MB 3.1 MB/s eta 0:00:05
   ------ --------------------------------- 2.4/15.1 MB 3.1 MB/s eta 0:00:05
   -------- ------------------------------- 3.1/15.1 MB 3.2 MB/s eta 0:00:04
   --------- ------------------------------ 3.7/15.1 MB 3.0 MB/s eta 0:00:04
   ----------- ---------------------------- 4.2/15.1 MB 3.0 MB/s eta 0:00:04
   ------------ --------------------------- 4.7/15.1 MB 3.0 MB/s eta 0:00:04
   ------------- -------------------------- 5.2/15.1 MB 3.0 MB/s eta 0:00:04
   --------------- ------------------------ 5.8/15.1 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 6.3/15.1 MB 2.8 MB/s eta 0:00:04
   ------------------ --------------------- 6.8/15.1 MB 2.8 MB/s eta 0:00:04
   ------------------ --------------------- 7.1/15.1 MB 2.7 MB/s eta 0:00:03
   -------------------- ------------------- 7.6/15.1 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 7.9/15.1 MB 2.6 MB/s eta 0:00:03
   ---------------------- ----------------- 8.4/15.1 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 8.7/15.1 MB 2.5 MB/s eta 0:00:03
   ------------------------ --------------- 9.2/15.1 MB 2.4 MB/s eta 0:00:03
   ------------------------- -------------- 9.7/15.1 MB 2.4 MB/s eta 0:00:03
   -------------------------- ------------- 10.0/15.1 MB 2.4 MB/s eta 0:00:03
   --------------------------- ------------ 10.5/15.1 MB 2.4 MB/s eta 0:00:02
   ----------------------------- ---------- 11.0/15.1 MB 2.4 MB/s eta 0:00:02
   ------------------------------ --------- 11.5/15.1 MB 2.4 MB/s eta 0:00:02
   ------------------------------- -------- 12.1/15.1 MB 2.4 MB/s eta 0:00:02
   --------------------------------- ------ 12.6/15.1 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 13.1/15.1 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 13.6/15.1 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 14.2/15.1 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  14.9/15.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 15.1/15.1 MB 2.4 MB/s  0:00:06
Downloading importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Installing collected packages: importlib_resources, sweetviz

   -------------------- ------------------- 1/2 [sweetviz]
   ---------------------------------------- 2/2 [sweetviz]

Successfully installed importlib_resources-7.1.0 sweetviz-2.3.3
Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (1.16.2)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (2.3.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pydantic<3,>=2 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (2.11.9)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (2.3.3)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\samba\miniconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Collecting seaborn<0.14,>=0.10.1 (from ydata-profiling)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.5.2-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<0.63,>=0.60 (from ydata-profiling)
  Downloading numba-0.62.1-cp313-cp313-win_amd64.whl.metadata (2.9 kB)
Collecting PyWavelets (from imagehash==4.3.2->ydata-profiling)
  Downloading pywavelets-1.9.0-cp313-cp313-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in c:\users\samba\miniconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\samba\miniconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\samba\appdata\roaming\python\python313\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\samba\miniconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\samba\appdata\roaming\python\python313\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba<0.63,>=0.60->ydata-profiling)
  Downloading llvmlite-0.45.1-cp313-cp313-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\samba\miniconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\samba\miniconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Collecting joblib>=0.14.1 (from phik<0.13,>=0.12.5->ydata-profiling)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\samba\miniconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\samba\miniconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\samba\miniconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\samba\miniconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\samba\miniconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\samba\miniconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\samba\miniconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\samba\miniconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.10.5)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: colorama in c:\users\samba\appdata\roaming\python\python313\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\samba\miniconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\samba\miniconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\samba\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.0 MB 3.8 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/8.0 MB 4.1 MB/s eta 0:00:02
   ------------- -------------------------- 2.6/8.0 MB 4.2 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.0 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.0 MB 4.3 MB/s eta 0:00:01
   -------------------------- ------------- 5.2/8.0 MB 4.2 MB/s eta 0:00:01
   ------------------------------ --------- 6.0/8.0 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 3.8 MB/s  0:00:02
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.62.1-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.7 MB 4.0 MB/s eta 0:00:01
   ---------------------- ----------------- 1.6/2.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 3.5 MB/s  0:00:00
Downloading llvmlite-0.45.1-cp313-cp313-win_amd64.whl (38.1 MB)
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
    --------------------------------------- 0.8/38.1 MB 3.4 MB/s eta 0:00:11
   - -------------------------------------- 1.6/38.1 MB 3.6 MB/s eta 0:00:11
   -- ------------------------------------- 2.4/38.1 MB 3.8 MB/s eta 0:00:10
   --- ------------------------------------ 3.4/38.1 MB 3.9 MB/s eta 0:00:09
   ---- ----------------------------------- 3.9/38.1 MB 3.7 MB/s eta 0:00:10
   ---- ----------------------------------- 4.7/38.1 MB 3.7 MB/s eta 0:00:09
   ----- ---------------------------------- 5.5/38.1 MB 3.8 MB/s eta 0:00:09
   ------ --------------------------------- 6.0/38.1 MB 3.7 MB/s eta 0:00:09
   ------ --------------------------------- 6.6/38.1 MB 3.7 MB/s eta 0:00:09
   ------- -------------------------------- 7.3/38.1 MB 3.6 MB/s eta 0:00:09
   -------- ------------------------------- 7.9/38.1 MB 3.5 MB/s eta 0:00:09
   -------- ------------------------------- 8.4/38.1 MB 3.5 MB/s eta 0:00:09
   --------- ------------------------------ 9.2/38.1 MB 3.4 MB/s eta 0:00:09
   ---------- ----------------------------- 9.7/38.1 MB 3.3 MB/s eta 0:00:09
   ---------- ----------------------------- 10.0/38.1 MB 3.2 MB/s eta 0:00:09
   ----------- ---------------------------- 10.7/38.1 MB 3.2 MB/s eta 0:00:09
   ----------- ---------------------------- 11.0/38.1 MB 3.1 MB/s eta 0:00:09
   ----------- ---------------------------- 11.0/38.1 MB 3.1 MB/s eta 0:00:09
   ----------- ---------------------------- 11.3/38.1 MB 2.8 MB/s eta 0:00:10
   ------------ --------------------------- 11.5/38.1 MB 2.7 MB/s eta 0:00:10
   ------------ --------------------------- 11.8/38.1 MB 2.7 MB/s eta 0:00:10
   ------------ --------------------------- 12.1/38.1 MB 2.6 MB/s eta 0:00:10
   ------------ --------------------------- 12.3/38.1 MB 2.5 MB/s eta 0:00:11
   ------------- -------------------------- 12.8/38.1 MB 2.5 MB/s eta 0:00:10
   -------------- ------------------------- 13.4/38.1 MB 2.5 MB/s eta 0:00:10
   -------------- ------------------------- 13.6/38.1 MB 2.5 MB/s eta 0:00:10
   --------------- ------------------------ 14.4/38.1 MB 2.5 MB/s eta 0:00:10
   --------------- ------------------------ 14.7/38.1 MB 2.5 MB/s eta 0:00:10
   --------------- ------------------------ 15.2/38.1 MB 2.5 MB/s eta 0:00:10
   ---------------- ----------------------- 15.7/38.1 MB 2.5 MB/s eta 0:00:10
   ---------------- ----------------------- 15.7/38.1 MB 2.5 MB/s eta 0:00:10
   ---------------- ----------------------- 16.0/38.1 MB 2.4 MB/s eta 0:00:10
   ----------------- ---------------------- 16.3/38.1 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.3/38.1 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/38.1 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/38.1 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.8/38.1 MB 2.2 MB/s eta 0:00:10
   ------------------ --------------------- 17.6/38.1 MB 2.2 MB/s eta 0:00:10
   ------------------ --------------------- 17.8/38.1 MB 2.2 MB/s eta 0:00:10
   ------------------- -------------------- 18.4/38.1 MB 2.2 MB/s eta 0:00:10
   ------------------- -------------------- 18.9/38.1 MB 2.2 MB/s eta 0:00:09
   -------------------- ------------------- 19.1/38.1 MB 2.1 MB/s eta 0:00:09
   -------------------- ------------------- 19.4/38.1 MB 2.1 MB/s eta 0:00:09
   -------------------- ------------------- 19.9/38.1 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 20.2/38.1 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 20.7/38.1 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 21.0/38.1 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 21.0/38.1 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 21.0/38.1 MB 2.1 MB/s eta 0:00:09
   ---------------------- ----------------- 21.5/38.1 MB 2.0 MB/s eta 0:00:09
   ----------------------- ---------------- 22.0/38.1 MB 2.0 MB/s eta 0:00:08
   ----------------------- ---------------- 22.5/38.1 MB 2.0 MB/s eta 0:00:08
   ------------------------ --------------- 23.3/38.1 MB 2.1 MB/s eta 0:00:08
   ------------------------- -------------- 23.9/38.1 MB 2.1 MB/s eta 0:00:07
   ------------------------- -------------- 24.6/38.1 MB 2.1 MB/s eta 0:00:07
   -------------------------- ------------- 25.4/38.1 MB 2.1 MB/s eta 0:00:06
   --------------------------- ------------ 26.2/38.1 MB 2.2 MB/s eta 0:00:06
   ---------------------------- ----------- 27.0/38.1 MB 2.2 MB/s eta 0:00:06
   ----------------------------- ---------- 28.0/38.1 MB 2.2 MB/s eta 0:00:05
   ----------------------------- ---------- 28.3/38.1 MB 2.2 MB/s eta 0:00:05
   ------------------------------ --------- 28.8/38.1 MB 2.2 MB/s eta 0:00:05
   ------------------------------ --------- 29.4/38.1 MB 2.2 MB/s eta 0:00:04
   ------------------------------- -------- 30.1/38.1 MB 2.2 MB/s eta 0:00:04
   ------------------------------- -------- 30.4/38.1 MB 2.2 MB/s eta 0:00:04
   -------------------------------- ------- 31.5/38.1 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 32.0/38.1 MB 2.3 MB/s eta 0:00:03
   ---------------------------------- ----- 32.5/38.1 MB 2.3 MB/s eta 0:00:03
   ---------------------------------- ----- 33.3/38.1 MB 2.3 MB/s eta 0:00:03
   ----------------------------------- ---- 34.1/38.1 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 34.6/38.1 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 34.9/38.1 MB 2.3 MB/s eta 0:00:02

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\SamBa\miniconda3\Lib\site-packages\~atplotlib'.
  You can safely remove it manually.

In [111]:
from seaborn import load_dataset

df = load_dataset("penguins")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [113]:
import sweetviz as sv

report = sv.analyze(df)
report.show_html("penguins_report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report penguins_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [118]:
my_report = sv.compare_intra(df, df["sex"] == "Male", ["Male", "Female"])

                                             |          | [  0%]   00:00 -> (? left)

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="EDA report", explorative=True)
profile.to_file("ydata_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]